### ISSUE TITLE
Card becomes blank upon refresh

### ISSUE THREAD

**Issue by vaidyasr** [gadgetchnnel/lovelace-card-templater#10]
Am trying to use the icon_template for my card to show the battery icon according to charging or not. The card shows fine, but after few seconds, the state value becomes blank. I have tried the below without the templating works fine.
```
card:
  animation: 'off'
  columns: 4
  direction: up
  entities:
    - entity: sensor.battery_level_x1
      icon_template: >-
        {% if (state_attr('device_tracker.google_maps_12345',
        'battery_charging') == True ) %} 
         mdi:battery-charging
         {% else %}
         mdi:battery
         {% endif %}
      title: X1
    - entity: sensor.battery_level_x2
      icon_template: >-
        {% if (state_attr('device_tracker.google_maps_67890',
        'battery_charging') == True ) %} 
         mdi:battery-charging
         {% else %}
         mdi:battery
         {% endif %}
      title: X2
    - entity: sensor.battery_level_x3
      icon_template: >-
        {% if (state_attr('device_tracker.google_maps_23456',
        'battery_charging') == True ) %} 
         mdi:battery-charging
         {% else %}
         mdi:battery
         {% endif %}
      title: X3
    - entity: sensor.battery_level_x4
      icon_template: >-
        {% if (state_attr('device_tracker.google_maps_45678',
        'battery_charging') == True ) %} 
         mdi:battery-charging
         {% else %}
         mdi:battery
         {% endif %}
      title: X4
  height: 200px
  icon_position: inside
  max: 100
  min: 0
  padding: 2px
  severity:
    - color: red
      value: 20
    - color: orange
      value: 50
    - color: green
      value: 100
  target: 80
  title_position: inside
  type: 'custom:bar-card'
  unit_of_measurement: '%'
  width: 100%
entities:
  - entity: sensor.battery_level_x1
  - entity: sensor.battery_level_x2
  - entity: sensor.battery_level_x3
  - entity: sensor.battery_level_x4
type: 'custom:card-templater'
```

**Comment by gadgetchnnel** [comment]
It's possible that this is due to you having the sensor.battery_level_x* sensors in the entities collection of the card-templater, which will cause it to refresh the template whenever these change. Since the template is based on the device_tracker.google_maps_* entities you should probably use those instead like this:

```yaml
card:
  animation: 'off'
  columns: 4
  direction: up
  entities:
    - entity: sensor.battery_level_x1
      icon_template: >-
        {% if (state_attr('device_tracker.google_maps_12345',
        'battery_charging') == True ) %} 
         mdi:battery-charging
         {% else %}
         mdi:battery
         {% endif %}
      title: X1
    - entity: sensor.battery_level_x2
      icon_template: >-
        {% if (state_attr('device_tracker.google_maps_67890',
        'battery_charging') == True ) %} 
         mdi:battery-charging
         {% else %}
         mdi:battery
         {% endif %}
      title: X2
    - entity: sensor.battery_level_x3
      icon_template: >-
        {% if (state_attr('device_tracker.google_maps_23456',
        'battery_charging') == True ) %} 
         mdi:battery-charging
         {% else %}
         mdi:battery
         {% endif %}
      title: X3
    - entity: sensor.battery_level_x4
      icon_template: >-
        {% if (state_attr('device_tracker.google_maps_45678',
        'battery_charging') == True ) %} 
         mdi:battery-charging
         {% else %}
         mdi:battery
         {% endif %}
      title: X4
  height: 200px
  icon_position: inside
  max: 100
  min: 0
  padding: 2px
  severity:
    - color: red
      value: 20
    - color: orange
      value: 50
    - color: green
      value: 100
  target: 80
  title_position: inside
  type: 'custom:bar-card'
  unit_of_measurement: '%'
  width: 100%
entities:
  - entity: device_tracker.google_maps_12345
  - entity: device_tracker.google_maps_67890
  - entity: device_tracker.google_maps_23456
  - entity: device_tracker.google_maps_45678
type: 'custom:card-templater'
```
