### ISSUE TITLE
wont work with auto-entities?

### ISSUE THREAD

**Issue by Mariusthvdb** [gadgetchnnel/lovelace-card-templater#13]
HI,

trying to have the auto-entities card use your card-templates to auto fill a list of entities, I am stuck. This is what I am trying to do:
```
  - type: custom:auto-entities
    card:
      type: entities
#      title: Github repos
      show_header_toggle: false
      header:
        type: picture
        image: /local/images/github_owler.png
    entities:
      - entity: automation.github_repo_update
        secondary_info: last-triggered
    filter:
      include:
        - entity_id: sensor.github*
          options:
            type: custom:card-templater
            state_template: >
              {% if state_attr(config.entity,'latest_release_url') %}
              {{ state_attr(config.entity,'latest_release_url').split('tag/')[1]}}
              {% else %} Not set
              {% endif %}
```

but apparently I need something else. No matter what I try, I can't get the list of GitHub sensors to show.

Please have a look how to realize this?
thanks!

**Comment by Mariusthvdb** [comment]
after some more experimenting, I must conclude something else to be preventing this to work.

even with a single spelled out entity, the templates dont do their work:

```
  - type: custom:card-templater
    card:
      type: entities
      title: Github repos
      show_header_toggle: false
      header:
        type: picture
        image: /local/images/github_owler.png
      entities:
        - entity: automation.github_repo_update
          secondary_info: last-triggered
        - entity: sensor.github_decluttering_card
          state_template: >-
            {% if state_attr('sensor.github_decluttering_card','latest_release_url') %}
            {{ state_attr('sensor.github_decluttering_card','latest_release_url').split('tag/')[1]}}
            {% else %} Not set
            {% endif %}
          secondary_info_template: >-
              {{ state_attr('sensor.github_decluttering_card','latest_commit_message')}}
```

shows as:

<img width="443" alt="Schermafbeelding 2020-02-24 om 08 49 18" src="https://user-images.githubusercontent.com/33354141/75135664-91fb8900-56e2-11ea-963b-37fda8a838b8.png">


while the sensor should show as:

<img width="440" alt="Schermafbeelding 2020-02-24 om 08 49 50" src="https://user-images.githubusercontent.com/33354141/75135690-a3dd2c00-56e2-11ea-9938-bd73c02cc51e.png">


this is the full sensor:

<img width="355" alt="Schermafbeelding 2020-02-24 om 08 44 42" src="https://user-images.githubusercontent.com/33354141/75135696-ad669400-56e2-11ea-965d-b1655f7f78a8.png">

please have a look why this wont work? My config seems to follow the docs 100%, or what am I missing.

secondly, could you make the card work in a way it can use  'entity' in the templates:

```
        - entity: sensor.github_decluttering_card
          state_template: >-
            {% if state_attr(entity, 'latest_release_url') %}
            {{ state_attr(entity, 'latest_release_url').split('tag/')[1]}}
            {% else %} Not set
            {% endif %}
          secondary_info_template: >-
              {{ state_attr(entity, 'latest_commit_message')}}
```

this would allow for great flexibilty and hopefully make it useable in the auto-entities card.
thanks for checking and considering.

**Comment by gadgetchnnel** [comment]
I looks like this shopuld work:
type: 'custom:auto-entities'
card:
  type: entities
  show_header_toggle: false
  header:
    type: picture
    image: /local/images/github_owler.png
  entities:
    - entity: automation.github_repo_update
       secondary_info: last-triggered
filter:
  include:
    - entity_id: sensor.github_*
      options:
        type: 'custom:card-templater'
        card:
          type: 'custom:hui-sensor-entity-row'
          entity: this.entity_id
        entities:
          - entity: this.entity_id
            state_template: >
              {% if state_attr("this.entity_id",'latest_release_url') %} {{
              state_attr("this.entity_id",'latest_release_url').split('tag/')[1]}}
              {% else %} Not set {% endif %}

(This works because the auto-entities card automatically replaces any instance of **this.entity_id** with the current entity)

Templating **secondary_info** doesn't really seem that it will do what you want as, looking at the documentation for the entities card, it describes it as follows:

> Show additional info. Values: entity-id, last-changed, last-triggered (only for automations and scripts).

So you can't just use it to display arbitrary information. However, you may be able to use [secondaryinfo-entity-row](https://github.com/custom-cards/secondaryinfo-entity-row) to do this.

**Comment by gadgetchnnel** [comment]
> well, it should, but it doesn't work.... 

This works for me, are you sure that all your GitHub sensors have entity ids in the format **sensor.github_*whatever***? Mine don't, and the only way I found to filter all the GitHub sensors in auto-entities was this:

```
filter:
  include:
    - attributes:
        icon: 'mdi:github-circle'
```
> I think the state_template should use this.entity_id, and not 'this.entity_id' but even if it is quoted it should use the electrical clause and show Not set.. which it doesn't.

The auto-entities card just seems to do a simple replace of the string **this.entity_id** with the entity id. This means that whether it should be wrapped in quotes depends on whether you would need quotes if you were using it with a hardcoded entity id. For example:

state_attr('this.entity_id','latest_release_url') => state_attr('sensor.github_decluttering_card','latest_release_url')

states.this.entity_id.state =>states.sensor.github_decluttering_card.state


> 
> this is all:
> 
> <img alt="Schermafbeelding 2020-02-25 om 01 38 37" width="339" src="https://user-images.githubusercontent.com/33354141/75203850-98841200-576f-11ea-9609-1575a361d0aa.png">
> 
> using
> 
> ```
>   - type: 'custom:auto-entities'
>     card:
>       type: entities
>       show_header_toggle: false
>       title: Github repos templater
>       header:
>         type: picture
>         image: /local/images/github_owler.png
>       entities:
>         - entity: automation.github_repo_update
>           secondary_info: last-triggered
>     filter:
>       include:
>         - entity_id: sensor.github_*
>           options:
>             type: 'custom:card-templater'
>             card:
>               type: 'custom:hui-sensor-entity-row'
>               entity: this.entity_id
>             entities:
>               - entity: this.entity_id
>                 state_template: >
>                   {% if state_attr('github_decluttering_card','latest_release_url') %} {{
>                   state_attr('github_decluttering_card','latest_release_url').split('tag/')[1]}}
>                   {% else %} Not set {% endif %}
> ```
> 
> (note Ive even filled a real sensor, to make sure this template isn't the culprit of things going wrong.)
> 

It looks like there you are missing the **sensor.** from the entity ids in state_attr, so the state_template should be more like:

state_template: >
  {% if state_attr('sensor.github_decluttering_card','latest_release_url') %} {{
       state_attr('sensor.github_decluttering_card','latest_release_url').split('tag/')[1]}}
  {% else %} Not set {% endif %}

> btw hope you can take out the required entity below the card: type: custom:card-template and move that to the template, (and only if really necessary, which it isn't in this case))

I need to work out if that is possible, as there is not an obvious way of determining which parameters are required.
One way I may be able to do it is by having an **entity_row** option which works the same as the **card** option which would be used if you want to template an entity row rather than a card. The entity would then be passed if templating an entity row but not if templating a card.
With this, the config would be something like:

```
options:
  type: 'custom:card-templater'
  entity_row:
    type: 'custom:hui-sensor-entity-row'
  entities:
     ...
```
Does that seem like it would help?

**Comment by Mariusthvdb** [comment]
yeah, Ive set the   entity_namespace: Github so all my sensors look like that. This proves the instance cn find them all:

<img width="399" alt="Schermafbeelding 2020-02-25 om 23 11 45" src="https://user-images.githubusercontent.com/33354141/75292354-4224db00-5824-11ea-98dc-a40314d158f6.png">
in another card config though, using template-entity-row:

```
  - type: custom:auto-entities
    card:
      type: entities
#      title: Github repos
      show_header_toggle: false
      header:
        type: picture
        image: /local/images/github_owler.png
    entities:
      - entity: automation.github_repo_update
        secondary_info: last-triggered
      - type: custom:template-entity-row
        name: >
          {{state_attr('sensor.home_assistant','name')}}
        icon: >
          {{state_attr('sensor.home_assistant','icon')}}
        state: >
          {% if state_attr('sensor.home_assistant','latest_release_url') %}
          {{ state_attr('sensor.home_assistant','latest_release_url').split('tag/')[1]}}
          {% else %} Not set
          {% endif %}
        secondary: >
          {{ state_attr('sensor.home_assistant','latest_commit_message')}}
    filter:
      include:
        - entity_id: sensor.github*
          options:
#            tap_action:
#              action: more-info
            type: custom:template-entity-row
            state: >
              {% if state_attr(config.entity,'latest_release_url') %}
              {{ state_attr(config.entity,'latest_release_url').split('tag/')[1]}}
              {% else %} Not set
              {% endif %}
            secondary: >
              {{ state_attr(config.entity,'latest_commit_message')}}
```
nb: note the unquoted config.entity which leads me to the following about the quoting of this.entity_id: isn't this a variable, which should never be quoted in these templates? Only quote if one has an actual entity_id there. I compared to another card, eg:
```
  - type: 'custom:auto-entities'
    card:
      type: entities
    filter:
      include:
        - entity_id: sensor.*_trash_timestamp
          options:
            type: custom:template-entity-row
            state: >
              {{state_attr(config.entity,'date')}}
    sort:
      method: state
```
but, confess, that didn't work either using your template card...

in the verbose test I indeed missed the 'sensor.' and will try later and report back if that does work.

about the entity_id needed in the templates: it is rather easy imho: most of the templates work right out of the box, with the obvious exception of now(), which doesn't cause a state change without adding an entity_id. most of the time sensor.time is used.

Id say the field should be optional, (in the template section to make it much easier configurable) so users can add the entity_id on a need-basis.
tanks for your time! much appreciated.

**Comment by gadgetchnnel** [comment]
@Mariusthvdb The 0.0.8 release version includes an undocumented change, which you can use **entity_row** instead of **card** if you want to template a row. Using this should pass the entity from **card-templater** to the row so you can do this:

```
- type: custom:auto-entities
   card:
     type: entities
     show_header_toggle: false
       entities:
   filter:
      include:
        - entity_id: sensor.github_*
          options:
            type: 'custom:card-templater'
            entity_row:
              type: 'custom:hui-sensor-entity-row'
            entities:
              - entity: this.entity_id
                 state_template: >-
                   {%- if state_attr('this.entity_id','latest_release_url') -%} {{
                   state_attr('this.entity_id',latest_release_url').split('tag/')[1]}}
                   {%- else -%} Not set {%- endif -%}
```
Currently, the entity id isn't directly accessibly as a template variable so you still need to rely on the "this.entity_id" auto replacement from auto-entities but I should be able to include that in the next release.

**Comment by Mariusthvdb** [comment]
thx!

I've edited the template a bit and added a second template in the else clause:

```
  - type: custom:auto-entities
    card:
      type: entities
      show_header_toggle: false
    filter:
      include:
        - entity_id: sensor.github_*
          options:
            type: 'custom:card-templater'
            entity_row:
              type: 'custom:hui-sensor-entity-row'
            entities:
              - entity: this.entity_id
                state_template: >-
                   {%- if state_attr('this.entity_id','latest_release_url') -%}
                   {{state_attr('this.entity_id','latest_release_url').split('tag/')[1]}}
                   {%- else -%} {{state_attr('this.entity_id','latest_commit_sha')[0:7]}}
                   {%- endif -%}
```
this actually works, but it completely halts my browsers. Safari showing the beachball, and freezing window. Chrome is a bit better, in that it doesn't freeze the window, but it grinds to an ultimate slow response. More info only pops up after many seconds if at all.

something definitely is eating resources in this card, can't even load inspector to see what's happening... have to take the card out again for now, hope you can fix this.

Btw, would you be willing to add templating for the secondary_info to, (preferably so it can template to any string we want, not necessarily what the core entities card provides?)

just for the sake of the correct templates:

<img width="343" alt="Schermafbeelding 2020-03-08 om 22 58 08" src="https://user-images.githubusercontent.com/33354141/76171891-78e9e200-6190-11ea-9ee3-b94afc09f272.png">
