### ISSUE TITLE
Is it possible to create a list of entities?

### ISSUE THREAD

**Issue by wsw70** [gadgetchnnel/lovelace-card-templater#15]
I have a variable list of entities in a card and tried to iterate over them in a template (all the examples show a predictable list of entities):

```
(...)
cards:
  - type: 'custom:card-templater'
    card:
      type: entities
      entities: 
      >-
        {% for state in states.sensor %}
        - entity: {{ state.name }}
        {% endfor %}
  - card: glance card
    columns: 3
    entities:
    - entity: monitoring.http_home_assistant
    - entity: monitoring.http_jackett
```

I left the next entry (a `glance card` to show in the screenshot below that that card is rendered correctly)

This generates an error in the frontend:
![image](https://user-images.githubusercontent.com/1345886/77251946-b56a1300-6c51-11ea-9052-cdb955d342a7.png)

Is there a way to iterate over a list and generate the relevant configuration?

**Comment by gadgetchnnel** [comment]
One thing, you need to use **entities_template** and not **entities**.  Also, it is easier to do it like this:

```
(...)
cards:
  - type: 'custom:card-templater'
    card:
      type: entities
      entities_template: >-
        {{ states.sensor | map(attribute="entity_id") | list | tojson }}
        
  - card: glance card
    columns: 3
    entities:
    - entity: monitoring.http_home_assistant
    - entity: monitoring.http_jackett
```
