### ISSUE TITLE
Card not being refreshed when attributes of entities change

### ISSUE THREAD

**Issue by legomind** [gadgetchnnel/lovelace-card-templater#18]
In the below example, the card does not refresh when the attributes of `sensor.irrigation_controller_status` change

``` yaml
type: 'custom:card-templater'
entities:
  - sensor.irrigation_controller_status
card:
  type: 'custom:vertical-stack-in-card'
  cards:
    - type: entities
      entities:
        - entity: sensor.irrigation_controller_status
          type: 'custom:secondaryinfo-entity-row'
          secondary_info_template: |-
            {% if(states.sensor.irrigation_controller_status.state != 'Idle') %}
              {{ states.sensor.irrigation_controller_status.attributes.current_zone }}
            {% endif %}
```
