### ISSUE TITLE
Error: Custom element not found: card-templater

### ISSUE THREAD

**Issue by mykorabel** [gadgetchnnel/lovelace-card-templater#19]
Home-assistant: 0.110.3, core on docker
HACS version: | 1.0.3
Frontend version: 202005242033
Lovelace Card Templater version: 0.0.10

Templater doesn't on fresh installation of HASS (throws the error: Custom element not found: card-templater). Rebooting hass doesn't help.

![Overview - Home Assistant 2020-06-01 11-10-19](https://user-images.githubusercontent.com/4049388/83390665-f40f0d00-a3fa-11ea-8e8b-055f50d684b3.png)

**Comment by gadgetchnnel** [comment]
@mykorabel Can you check some things:

- Make sure it is showing (under Configuration > Lovelace Dashboards > Resources if you use Storage mode for Lovelace or under lovelace -> resources in configuration.yaml if you use YAML mode)
- Are there any errors in the Javascript console in the your browser or in the home-assistant.log file?

If there are no errors and/or it doesn't appear to be showing under your resources, try uninstalling and re-installing it in HACS. I've found that sometimes a custom card hasn't installed correctly and doing that has helped.

**Comment by mykorabel** [comment]
@gadgetchnnel thanks, 
seems to be HACS issue.

**Comment by TheGroundZero** [comment]
I installed this custom card from HACS as well and I'm also getting this error.

Version 0.0.12  
Already did reinstall from HACS

```yaml
type: 'custom:card-templater'
card:
  type: picture-entity
  name_template: '{{ states.sensor.bio.attributes.days }} days'
  show_name: true
  show_state: false
  entity: sensor.bio
  state_image:
    '0': /local/img/garbage/afval-papier_bw.png
    '1': /local/img/garbage/afval-papier.png
    '2': /local/img/garbage/afval-papier_now.png
entities:
  - sensor.bio
```
`Custom element not found: card-templater`

Resources are installed at /config/lovelace/resources

![image](https://user-images.githubusercontent.com/2406013/90816225-7385eb80-e31b-11ea-877a-da05b87ef2dd.png)
