### ISSUE TITLE
Get an error box on screen updates

### ISSUE THREAD

**Issue by finity69x2** [gadgetchnnel/lovelace-card-templater#20]
I'm getting an occasional red error box on screen updates in the Lovelace UI.

It is fixed by doing a browser refresh.

I posted about this in the forum thread but got no response so I'm posting it here.

Here is a screenshot of the error:

![ex1](https://user-images.githubusercontent.com/32221243/86606163-a9daf780-bf75-11ea-9096-5ff5801eef2f.gif)

**Comment by gadgetchnnel** [comment]
What is the full template you have for the **name_template**?
It looks like that is referring to a sensor (it starts with "{{ states.sensor") and that sensor will also need to be added to the **entities** collection of or card-templater so it knows to listen for changes to it.

**Comment by finity69x2** [comment]
Here is the entire code for the card:

```
- type: 'custom:card-templater'
    card:
      type: entity-filter
      show_empty: false
      card: 
        type: glance
        state_color: true
      state_filter: 
        - "on"
      entities:
        - binary_sensor.water_heater_not_ok
        - binary_sensor.ha_update_avail_template
        - binary_sensor.potential_breaking_changes
        - entity: binary_sensor.nuc_memory_usage_high
          name_template: "NUC High Memory Usage - {{ states.sensor.memory_use_percent.state }}%"
        - binary_sensor.haapi_mqtt_test
        - input_boolean.low_batteries
    entities:
      - entity: binary_sensor.nuc_memory_usage_high
```

It doesn't contain a name_template.

And the error doesn't ever occur unless I reload lovelace for a change in the frontend config or very occasionally when I switch from the tab to another and back again.

A ctrl-F5 refresh always fixes it immediately.
