### ISSUE TITLE
graph disappears when I insert lovelace-card-templater

### ISSUE THREAD

**Issue by GHSTUDIO1** [gadgetchnnel/lovelace-card-templater#25]
I have a working card (custom:canvas-gauge-card'

I modify the yaml from:
```
views:
  - cards:
```

to:
```
views:
  - type: 'custom:card-templater'
    entities:
      - sensor.maverick_temp3
    card:
```

My graph no longer shows.  Note...I have not changed any name to name_template.

I have tried both card-templater and lovelace-card-templater .... neither works.

I have no logs...no idea how to debug this.

**Comment by gadgetchnnel** [comment]
It looks like you have lost the **cards** option from the view when you changed to use card-templater. It should look more like this:

```
views:
  - cards:
      - type: 'custom:card-templater'
        entities:
          - sensor.maverick_temp3
        card:
```
