### ISSUE TITLE
question - how do I change a value

### ISSUE THREAD

**Issue by GHSTUDIO1** [gadgetchnnel/lovelace-card-templater#26]
I would like to be able to change the from/to values in the following (creating a canvas-gauge)  based on user's input using a slider:
```
highlights:
            - color: 'rgba(239, 93, 13, .75)'
              from: 175
              to: 225
            - color: 'rgba(4, 205, 24, .75)'
              from: 225
              to: 350
            - color: 'rgba(239, 93, 13, .75)'
              from: 350
              to: 375
```

Can I use this add on?  How would I code it?

I know this isn't an issue...but is there a better way to reach the author?
