### ISSUE TITLE
When ApexChart wrapped in Card-Templater, the graph constantly redraws.

### ISSUE THREAD

**Issue by wigster** [gadgetchnnel/lovelace-card-templater#37]
Hi,

# Use case: 
I am using an ApexChart card to plot the output of a sensor. The sensor is down sometimes, so I would like to use card-templater to swap the sensor for a backup one. This works fine.

# Problem
However, the moment that I wrap an ApexChart in card-templater, even without any templates, the graph begins to redraw every few seconds and the viewport of the browser keeps moving around (the cards even get rearranged). I've reported it to ApexCharts, but I've been sent here

https://github.com/RomRider/apexcharts-card/issues/124

```yaml
type: 'custom:card-templater'
entities:
  - wu_dejvice_status
  - wu_podbaba_status
card:
  type: 'custom:apexcharts-card'
  series:
    - entity: sensor.wu_dejvice_temperature
      type: area
  graph_span: 24h
```
The two status trackers get updated once every 15 minutes, so should not be causing a redraw.
