### ISSUE TITLE
Cards not updating in real time

### ISSUE THREAD

**Issue by ankurpandeyvns** [gadgetchnnel/lovelace-card-templater#44]
The normal entities card got updated in real time whereas this isn't. Hoping for some guidance,,, 
And thanks for the awesome extension

**Comment by zanna-37** [comment]
I confirm the issue. Any card update that is not catched by entities fail to trigger the card update.
Adding every possible entity in the `entitites` field is just wrong because only entities used in the template should be placed there.

**Comment by gadgetchnnel** [comment]
There is an alpha version, 0.1.0-alpha2, which has refactored template handling which should handle entity changes better.

With this version, you should only need to use the **entities** option if you want to template the state of any of the entities or you want control over which entities will trigger a refresh of the templates.

**Comment by zanna-37** [comment]
Yes, I know, this issue is to state that the expected behavior is not met by the card-templater.
If a third-party card has logic to update itself (for example a chart), it will be completely overridden by the card-templater. In fact, using the card-templater the third-party card only refreshes when the card-templater decides so (which is when an entity in `entitites` changes).

Is it fixable or is it a technical issue with the way home-assistant works?

**Comment by gadgetchnnel** [comment]
@zanna-37 Have you tried with the latest alpha version?
Do you have an example of a card, with config if possible, that has this issue?

**Comment by zanna-37** [comment]
Basically every card does not update, but a minimum example is

```yaml
type: custom:card-templater
entities:
  - input_number.an_input_number_with_slider
card:
  type: entities
  entities:
    - entity: input_number.an_input_number_with_slider
      name_template: >
        {{ "I'm on" if is_state('binary_sensor.test', 'on') else "I'm off" }}
```
_Tested on v0.1.0-alpha2_

Try to adjust the slider and the number on the right will not reflect the new value. Notice that `input_number.an_input_number_with_slider` is not in the `entities` field, and that's because I don't need to template on that.

Tell me if you need screenshots.
