### ISSUE TITLE
Indentation of example in readme incorrect

### ISSUE THREAD

**Issue by TheFes** [gadgetchnnel/lovelace-card-templater#45]
```yaml
type: 'custom:card-templater'
card:
  ...
entities:
  - entity: sensor.my_sensor
     state_template: >
       {{ "One" if states.sensor.my_sensor.state == "1" else "Not One" }}
     attributes:
       unit_of_measurement_template: >
         {{ states.sensor.my_sensor_uom.state }}
```

The indentation of this example is incorrect. `state_template:` has one space indentation compared to `entity:`. The same applies to `attributes:`
