### ISSUE TITLE
Simple condition if not working

### ISSUE THREAD

**Issue by darkkatarsis** [gadgetchnnel/lovelace-card-templater#5]
Below example that im talking about. Could you help me with syntax?

`- type: 'custom:card-templater'
        card:
          type: 'custom:mini-graph-card'
          entities:
            - sensor.bedroom_temperature
          line_color: "{{ states.sensor.living_room_temperature|float <= 20 ? '#2980b9' : (states.sensor.living_room_temperature|float <= 22 ? '#b58e31' : '#b93829' ) }}"
          line_width: 4
          name: Test`

**Comment by gadgetchnnel** [comment]
You are missing a couple of things:

1. You need to add **_template** to the end of any option you want to set using a template.
2. The card-templater card itself also has an entities option, which should contain any entities you want to monitor for changes (it cannot determine this from the template like template sensors can).

This means your config should look something like this:

```
- type: 'custom:card-templater'
   card:
     type: 'custom:mini-graph-card'
     entities:
       - sensor.bedroom_temperature
     line_color_template: "{{ states.sensor.living_room_temperature|float <= 20 ? '#2980b9' : (states.sensor.living_room_temperature|float <= 22 ? '#b58e31' : '#b93829' ) }}"
     line_width: 4
     name: Test
  entities:
     - sensor.bedroom_temperature
```
Or, using the > character to allow better formatting of templates on multiple lines, like this:

```
- type: 'custom:card-templater'
   card:
     type: 'custom:mini-graph-card'
     entities:
       - sensor.bedroom_temperature
     line_color_template: >
       {{ states.sensor.living_room_temperature|float <= 20 ? '#2980b9' : 
       (states.sensor.living_room_temperature|float <= 22 ? '#b58e31' : 
       '#b93829' ) }}
     line_width: 4
     name: Test
  entities:
     - sensor.bedroom_temperature
```
