### ISSUE TITLE
Wrapped gauges jump to zero before updating to new value

### ISSUE THREAD

**Issue by StephanSchuster** [gadgetchnnel/lovelace-card-templater#51]
This updates seamlessly:

```
type: gauge
entity: sensor.solaredge_battery1_state_of_charge
name: Batterieladung
needle: true
min: 0
max: 100
severity:
  red: 0
  yellow: 15
  green: 50
```

Here the needle quickly jumps to 0 before moving to the new value:

```
type: custom:card-templater
card:
  type: gauge
  entity: sensor.solaredge_battery1_state_of_charge
  name: Batterieladung
  needle: true
  min: 0
  max: 100
  severity:
    red: 0
    yellow: 15
    green: 50
entities:
  - entity: sensor.solaredge_battery1_state_of_charge
    state_template: '{{ states("sensor.solaredge_battery1_state_of_charge") | round(0) }}'
```
This looks awkward and currently requires me to write a template sensor just to round the value.
