### ISSUE TITLE
iterating over lists cause multiline strings to appear

### ISSUE THREAD

**Issue by Zaunmich** [gadgetchnnel/lovelace-card-templater#58]
Heya,

this issue is kinda related to #15, but a bit different.

I am trying to create elements by iterating over a list, like this:

```yaml
type: custom:card-templater
entities:
  - entity: sensor.time
card:
  title: Areas with active lights
  type: picture-elements
  image: http://homeassistant.local:8123/local/floorplan.svg
  dark_mode_filter: invert(50%)
  elements_template: >-
    {% for room in [  
      ({'name': 'Kitchen', 'x': 10, 'y': 20}),
      ({'name': 'Living Room', 'x': 30, 'y': 40}),
    ] -%} 
    - type: icon
      icon: mdi:lightbulb
      style:
        top: {{room['x']}}%
        left: {{room['y']}}%
      title: {{room['name']}} lights. Tap to turn off    
    {% endfor -%}
```

However, this produces an unwanted `|-` statement ( = a multiline string in yaml) resulting in this code:

```yaml
title: Areas with active lights
type: picture-elements
image: http://homeassistant.local:8123/local/floorplan.svg
dark_mode_filter: invert(50%)
elements: |-                #<---this one right here
  - type: icon
    icon: mdi:lightbulb
    style:
      top: 10%
      left: 20%
    title: Kitchen lights. Tap to turn off    
  - type: icon
    icon: mdi:lightbulb
    style:
      top: 30%
      left: 40%
    title: Living Room lights. Tap to turn off
```

This causes the card to not render, as it treats everything after `|-` as a string...

Is there a way to suppress this behavior?

**Comment by MacDada** [comment]
I guess I'm having the same issue? I want a dynamic list of `cards` in `horizontal-stack`, but for now even this simple thing is not working:

```yaml
type: 'custom:card-templater'
card:
  type: horizontal-stack
  cards_template: |
    - entity: 'sensor.date_time_iso'
      type: 'entity'
```

<img width="1090" alt="Screenshot 2024-10-03 at 00 33 19" src="https://github.com/user-attachments/assets/8ecc3671-85c4-420a-ab81-b437ae89317c">

<img width="1093" alt="Screenshot 2024-10-03 at 00 33 37" src="https://github.com/user-attachments/assets/fd830a6c-9077-49c2-8ba3-753e9e281d51">

<img width="1098" alt="Screenshot 2024-10-03 at 00 33 50" src="https://github.com/user-attachments/assets/a9e5c259-7cec-4e71-8c08-941947439046">
