### ISSUE TITLE
templater not playing well with webrtc-camera card

### ISSUE THREAD

**Issue by GaryOkie** [gadgetchnnel/lovelace-card-templater#59]
I'm attempting to dynamically define an NVR camera URL for the [custom webrtc-camera card](https://github.com/AlexxIT/WebRTC) but the card rejects it.  It's saying "Missing url or entity" when the "_template" suffix is added.   The template is accepted just fine with the title_template option only.

```
type: custom:card-templater
entities:
  - input_select.nvr_channel
card:
  type: custom:webrtc-camera
  url_template: >-
    rtsp://admin:password@192.168.x.x:554/cam/realmonitor?channel={{states.input_select.nvr_channel.state}}&subtype=0
   title_template: >-
    Channel   = {{states.input_select.nvr_channel.state}}
```

It appears this may be a similar problem to other issues reported here with URL's not templating properly.    In this case, I guess it's just due to "_template" not being removed from "url" when passed on to the embedded card.   Here's a snippet of code where it rejects the unrecognized url_template...
```

Webrtc-camera.js
        let url = 'ws' + hass.hassUrl(data.path).substr(4);
        if (this.config.url) url += '&url=' + encodeURIComponent(this.config.url);

setConfig(config) {
        if (typeof config.url !== 'string' && typeof config.entity !== 'string') {
            throw new Error('Missing `url` or `entity`');
```
