### ISSUE TITLE
value_template does not work

### ISSUE THREAD

**Issue by weswitt** [gadgetchnnel/lovelace-card-templater#67]
using a value_template does not have any effect. using the following card yaml the value_template has sero effect. i've tried various code in the value_template but it just does nothing.

type: 'custom:card-templater'
card:
  type: entities
  show_header_toggle: false
  columns: 1
  title: Current Environmental
  entities:
    - entity: sensor.outside_temperature
      value_template: '{{ sensor.outside_temperature | round(0) }}'

**Comment by pkoevesdi** [comment]
I think You have to put it like this:
```
type: custom:card-templater
card:
  type: entities
  show_header_toggle: false
  columns: 1
  title: Current Environmental
entities:
  - entity: sensor.outside_temperature
    state_template: '{{ sensor.outside_temperature | round(0) }}'
```
