### ISSUE TITLE
Custom element doesn't exist: hui-iframe-card

### ISSUE THREAD

**Issue by radical-squared** [gadgetchnnel/lovelace-card-templater#68]
I keep getting the following error message when using the card: Custom element doesn't exist: hui-iframe-card.
![hui](https://user-images.githubusercontent.com/26088959/230591449-8ad19219-e3ea-44c4-8fbf-e1179ee20988.png)

The error occurs on versions 0.0.17 and alphas 2 & 3. 

Here's my setup:
```
type: custom:card-templater
card:
  type: iframe
  url_template: https://xxxx.yyy.zz/table.html?user={{user.name}}
  aspect_ratio: 100%
entities:
  - sun.sun
```
