### ISSUE TITLE
Template format for rgb colors in custom card

### ISSUE THREAD

**Issue by BarrettLowe** [gadgetchnnel/lovelace-card-templater#7]
I'm having some issues getting my rgb colors templated inside a custom card. The card is https://github.com/bokub/rgb-light-card. My code is below. What have I got wrong? I have gotten card-tools, the rgb light card, and this card templater from HACS. 

Typing this is gives me some yellow warnings but if I hit save anyway, my templates below turn into `[Object object]: null`. 

Ideas?

```
    - colors:
      - brightness: 255
        rgb_color:
          - string_template: {{ states("input_number.cabinet_nighttime_red") | int }} 
          - string_template: {{ states("input_number.cabinet_nighttime_green") | int }} 
          - string_template: {{ states("input_number.cabinet_nighttime_blue") | int }} 
        transition: 1
    entity: light.example_light
    type: 'custom:rgb-light-card''
```

**Comment by gadgetchnnel** [comment]
@BarrettLowe 
I think you either need to use **>** like this

```
type: 'custom:card-templater'
card:
  type: 'custom:rgb-light-card'
  colors:
    - brightness: 255
       rgb_color:
         - string_template: >
              {{ states("input_number.cabinet_nighttime_red") | int }} 
        - string_template: >
             {{ states("input_number.cabinet_nighttime_green") | int }} 
        - string_template:
             {{ states("input_number.cabinet_nighttime_blue") | int }} 
      transition: 1
  entity: light.example_light
entities:
  - light.example_light
```
or quote the templates like this

```
type: 'custom:card-templater'
card:
  type: 'custom:rgb-light-card'
  colors:
    - brightness: 255
       rgb_color:
         - string_template: '{{ states("input_number.cabinet_nighttime_red") | int }}'
         - string_template: '{{ states("input_number.cabinet_nighttime_green") | int }}'
         - string_template: '{{ states("input_number.cabinet_nighttime_blue") | int }}'
       transition: 1
  entity: light.example_light
entities:
  - light.example_light
```
Those work for me with that card.
