### ISSUE TITLE
Doesnt seem to be working anymore? name_template shows '-' 

### ISSUE THREAD

**Issue by daytonturner** [gadgetchnnel/lovelace-card-templater#70]
I'm using HA 2023.5, and I'm trying to use the templater card very similar to the example in the README:

```
type: custom:card-templater
card:
  type: entities
  title: 'Ferry: Langdale to Horseshoe Bay'
  entities:
    - entity: sensor.bc_ferries_langdale_to_horseshoe_bay_schedule_1
      type: custom:multiple-entity-row
      name_template: '{{ states.sensor.bc_ferries_langdale_to_horseshoe_bay_schedule_1_leave_by.state }}'
      show_state: false
      icon: mdi:ferry
```

The state of this sensor is a time string (9:07 PM) and instead, its displaying a - in place of the name.

It seems to do this regardless of what i put in name_template, or if i use a multiline >- config format,.. Tried different sensor entities.

I dont see any javascript errors in the console, and not sure where else to look.

Any suggestions?
