### ISSUE TITLE
Problem with picture-elements card: can't template position

### ISSUE THREAD

**Issue by Dtrotmw** [gadgetchnnel/lovelace-card-templater#71]
I'm trying to use card-templater to position a sensor state on a scale such that its location depends on another sensor's value.  This is my attempt:
```
type: custom:card-templater
entities:
  - sensor.wind_speed
  - sensor.wind_bft
  - sensor.wind_dir
  - sensor.wind_bftpct
card:
  type: picture-elements
  image: /local/images/bft.jpeg
  elements:
    - element: ''
      type: state-label
      entity: sensor.wind_speed
      prefix_template: '{{states("sensor.wind_bftpct")}}'
      style:
        top: 20%
        left_template: '{{states("sensor.wind_bftpct")}}'
``` 
if i replace the last line with ```left: 30%``` it works as expected proving that the templater is installed OK and is displaying the correct state of the sensor (a string; "30%").  Am I doing something wrong or does the templater not work this way for position?
